name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        mkdir -p test/keys
        openssl genrsa -out test/keys/ssl.key 2048
        openssl req -new -key test/keys/ssl.key -x509 -days 999 -out test/keys/ssl.cert
        npm run build --if-present
        npm test
      env:
        CI: true
